### ISSUE TITLE
ERROR: self.get_widgets()[next_widget_num] is None

### ISSUE THREAD

**Issue by voryzen** [jwlodek/py_cui#161] opened 2021-11-27 10:33 UTC
Updated to v0.1.4

Shifting focus through widgets, first cycle is fine, however py_cui program crashes and returns this error upon the second cycle.

`self.get_widgets()[next_widget_num] is None.`

Terminal shows this after crash

 ```
 File "/usr/lib/python3.9/site-packages/py_cui/__init__.py", line 316, in start
    curses.wrapper(self._draw)
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.9/site-packages/py_cui/__init__.py", line 1679, in _draw
    self._cycle_widgets()
  File "/usr/lib/python3.9/site-packages/py_cui/__init__.py", line 1123, in _cycle_widgets
    if self.get_widgets()[next_widget_num] is None:

```

Any ideas? @PabloLec

**Comment by PabloLec** [comment] 2021-11-29 08:57
I can't reproduce this behavior.
Using `v0.1.4` I can use the example scripts without any exception.

Could you also paste the error type? You just provided the traceback.
And do you have any code to be tested? In order to reproduce the error.

**Comment by voryzen** [comment] 2021-12-04 05:38
the only error output I get is:
`KeyError: 5`

I am getting this error, when I run my own local program that I'm building with py_cui.

**Comment by PabloLec** [comment] 2021-12-04 09:24
Ok, `root.set_widget_cycle_key(forward_cycle_key=py_cui.keys.KEY_TAB, reverse_cycle_key=None)` helped me to reproduce the behavior.
That was indeed a bug, just pushed a PR to fix it :wink:

**Comment by voryzen** [comment] 2021-12-04 10:31
Awesome @PabloLec 
Terrific work

**Comment by PabloLec** [comment] 2021-12-04 10:46
> Awesome @PabloLec Terrific work
> 
> Does this fix #121 ?

Yes indeed ! I didn't see that issue. Good call, I'll add it in the PR.

**Comment by voryzen** [comment] 2021-12-04 10:49
Thanks.

What about #116 ?

It may not be fixed, but it certainly related

**Comment by PabloLec** [comment] 2021-12-04 10:59
> Thanks.
> 
> What about #116 ?
> 
> It may not be fixed, but it certainly related

Not this one :smile: 
**This one should be closed by the way as it was resolved by #125** 
When cycling through widgets, `status_bar` get refreshed at some point which is expected behavior. Here, the user set status bar `None` in order to hide it. That caused an exception obviously. 
#125 introduced two new methods for `status_bar`, `.show()` and `.hide()` which will avoid the need to unset it. So now I guess raising an exception when `status_bar` is None is acceptable as there is no reason it should be.

**Comment by voryzen** [comment] 2021-12-04 11:03
Ahh, right.
Thanks for the info. It is helpful; I haven't coded with python before now

**Comment by PabloLec** [comment] 2021-12-04 11:10
Great to begin with a TUI :smiley: I also created my first open-source Python project that way.

**Comment by voryzen** [comment] 2021-12-04 12:27
That's cool.

I'm almost finished my first iteration with this project.
I just need to work out how to 'turn off' the CUI temporarily, and I'll be able to finish it and push

**Closed** 2021-12-06 05:25 UTC
